version: '3'
services:
  study-app:
    build:
      context: .
      dockerfile: Dockerfile.study
    container_name: study-app
    volumes:
      - .:/app
      # node_modulesはcreate-next-appしてからボリューム化する
    tty: true
    ports:
      - 3000:3000
      - 6006:6006
    command: sh -c "cd study-app && npm run dev"